plugins {
    id 'com.android.application'
}

android {
    namespace 'com.britixo.voip'
    compileSdk 36

    defaultConfig {
        applicationId 'com.britixo.voip'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0-test'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
